# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52503778475686b12de9f49917cda89324898dc7131df1992ddfd95feeaca1d0d7d74920d2de3e692b8ae3dda7436fae74bc46b1a38d82a548006d6e3bddc02d

test:
  secret_key_base: 9e94cdf0693c38a1a78505eb18a3d2dcb1e7e6054b8ee441bf0f7df045c2490e9a754c0931a7d09d75ae7d4c4024e7321ba7c315dfa8a014fb2e3c64a4db3444

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
